### ISSUE TITLE
Building docker image failed while installing pathlib.

### ISSUE THREAD

**Issue by ll7** [ignc-research/arena-rosnav-3D#36]
Building docker image failed:

```bash
arena-rosnav-3D/docker$ docker build --no-cache -t rosnav-3d:v1 .

...

Collecting netifaces
  Downloading netifaces-0.11.0-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.whl (33 kB)
Collecting pathlib
  Downloading pathlib-1.0.1.tar.gz (49 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 49.3/49.3 KB 8.4 MB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-u4rvo23q/pathlib_7d0200e8448443c4b46c5dcf16b38d91/setup.py", line 6, in <module>
          setup(
        File "/root/.python_env/rosnav/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 109, in setup
          _setup_distribution = dist = klass(attrs)
        File "/root/.python_env/rosnav/lib/python3.8/site-packages/setuptools/dist.py", line 460, in __init__
          for ep in metadata.entry_points(group='distutils.setup_keywords'):
        File "/root/.python_env/rosnav/lib/python3.8/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 999, in entry_points
          return SelectableGroups.load(eps).select(**params)
        File "/root/.python_env/rosnav/lib/python3.8/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 449, in load
          ordered = sorted(eps, key=by_group)
        File "/root/.python_env/rosnav/lib/python3.8/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 997, in <genexpr>
          dist.entry_points for dist in unique(distributions())
        File "/root/.python_env/rosnav/lib/python3.8/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 609, in entry_points
          return EntryPoints._from_text_for(self.read_text('entry_points.txt'), self)
        File "/root/.python_env/rosnav/lib/python3.8/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 917, in read_text
          return self._path.joinpath(filename).read_text(encoding='utf-8')
      AttributeError: 'PosixPath' object has no attribute 'read_text'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
The command '/bin/bash -c source /root/.bashrc     && source `which virtualenvwrapper.sh`     && mkvirtualenv --python=python3.8 rosnav     && workon rosnav     && pip3 install --extra-index-url https://rospypi.github.io/simple/ rospy rosbag tf tf2_ros --ignore-installed     && pip3 install pyyaml catkin_pkg netifaces pathlib filelock pyqt5 mpi4py torch lxml scipy defusedxml' returned a non-zero code: 1
```

**Comment by eliastreis** [comment]
This docker image is depreciated, as significant alterations have been done to the repo since its creation. If you want to use the repository I would recommend following the [install script](https://github.com/ignc-research/arena-rosnav-3D/blob/main/docs/Installation.md). 
There is also an updated docker image in this branch [here](https://github.com/ignc-research/arena-rosnav-3D/tree/arena-benchmark) which should work, but this branch does not include some recent developments

**Comment by ll7** [comment]
Thank you for the clarification.
